# -*- coding: utf-8 -*-
"""MDD-GSE248260

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AN4aMC7oGIqhucrdJc1jErcypCh6FXaG
"""

# Load downloaded file
expr_matrix <- read.csv("/content/GSE248260_white_matter_count_matrix.csv", header = TRUE, row.names = 1, check.names = FALSE)

# Validate
dim(expr_matrix)
str(expr_matrix)

expr_matrix <- expr_matrix[rowSums(expr_matrix > 1) >= 3, ]
dim(expr_matrix)  # Check the new dimensions

expr_matrix_log <- log2(expr_matrix + 1)

# Check the transformed data
dim(expr_matrix_log)  # View dimensions after transformation
summary(expr_matrix_log)  # Check summary statistics

# Perform PCA on the log-transformed expression matrix
pca_result <- prcomp(t(expr_matrix_log), scale. = TRUE)

# View summary of PCA result
summary(pca_result)

dim(expr_matrix)  # Check the number of rows

colData <- read.csv("/content/coldata.csv", header = TRUE, row.names = 1)
head(colData)

print(colData)
dim(colData)

# Convert PCA result into a data frame
pca_df <- as.data.frame(pca_result$x)

# Add Sample ID as a new column
pca_df$Sample_Label <- rownames(pca_df)

# Now map condition from colData
pca_df$Group <- colData[pca_df$Sample_Label, "condition"]

# Convert Group to a factor (for nice plotting)
pca_df$Group <- factor(pca_df$Group, levels = c("Normal", "MDD"))

# Preview
head(pca_df)

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ggplot2")

library(ggplot2)

scree_data <- data.frame(
  PC = 1:length(pca_result$sdev),
  Variance = (pca_result$sdev^2) / sum(pca_result$sdev^2)
)
ggplot(scree_data, aes(x = PC, y = Variance)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(title = "Scree Plot", x = "Principal Component", y = "Proportion of Variance")

#PCA scatter plot
ggplot(pca_df, aes(x = PC1, y = PC2, color = Group)) +
  geom_point(size = 4, alpha = 0.7) +  # Size and transparency of points
  theme_minimal() +  # Clean theme
  labs(title = "PCA: MDD Samples",
       x = paste0("PC1 (", round(summary(pca_result)$importance[2, 1] * 100, 1), "% Variance)"),
       y = paste0("PC2 (", round(summary(pca_result)$importance[2, 2] * 100, 1), "% Variance)"))

# Basic PCA scatter plot using base R
plot(pca_result$x[,1], pca_result$x[,2],
     xlab = "PC1", ylab = "PC2",
     main = "PCA of Gene Expression Data",
     col = "blue", pch = 19)  # Blue points with solid circles

# Adding sample labels to the plot
text(pca_result$x[,1], pca_result$x[,2], labels = colnames(expr_matrix), pos = 3, cex = 0.8)

library(ggplot2)

# Create PCA data frame with PC1, PC2 and Sample IDs
pca_df <- data.frame(PC1 = pca_result$x[,1],
                     PC2 = pca_result$x[,2],
                     Sample_Label = rownames(pca_result$x))  # Keep your real sample names (104A, etc.)

# Add Condition information from colData
pca_df$Condition <- colData[pca_df$Sample_Label, "condition"]

# Convert Condition to a factor for better plot colors
pca_df$Condition <- factor(pca_df$Condition, levels = c("Normal", "MDD"))

# PCA plot with real sample labels
ggplot(pca_df, aes(x = PC1, y = PC2, color = Condition)) +
  geom_point(size = 4, alpha = 0.7) +  # Scatter points
  geom_text(aes(label = Sample_Label), vjust = -1, size = 3) +  # Labels above points
  theme_minimal() +  # Clean minimal theme
  labs(title = "PCA: Normal vs MDD Samples",
       x = paste0("PC1 (", round(summary(pca_result)$importance[2, 1] * 100, 1), "% Variance)"),
       y = paste0("PC2 (", round(summary(pca_result)$importance[2, 2] * 100, 1), "% Variance)")) +
  theme(legend.position = "top") +  # Legend at the top
  scale_color_manual(values = c("Normal" = "blue", "MDD" = "red"))  # Customize color

str(pca_df)

# Install required packages (if not already installed)
# install.packages("patchwork")
install.packages("patchwork")

# Load libraries
library(ggplot2)
library(patchwork)

# Assuming your sample IDs and conditions are already loaded into coldata
# coldata should have two columns: Sample_Label and Condition

# Create the PCA dataframe
pca_df <- data.frame(
  PC1 = pca_result$x[,1],
  PC2 = pca_result$x[,2],
  PC3 = pca_result$x[,3],
  PC4 = pca_result$x[,4],
  PC5 = pca_result$x[,5],
  PC6 = pca_result$x[,6],
  PC7 = pca_result$x[,7]
)

# Add Sample_Label from coldata
pca_df$Sample_Label <- rownames(pca_result$x)  # assuming the rownames are your sample IDs like "104A", "109A", etc.

# Merge with coldata to get the Condition
# Suppose coldata has columns Sample_Label and Condition
pca_df <- merge(pca_df, colData, by.x = "Sample_Label", by.y = "row.names")

# Convert Condition to factor
pca_df$Condition <- factor(pca_df$condition, levels = c("Normal", "MDD"))

# Function to create PCA plots
create_pca_plot <- function(x, y) {
  ggplot(pca_df, aes_string(x = x, y = y, color = "Condition")) +
    geom_point(size = 4, alpha = 0.7) +
    geom_text(aes(label = Sample_Label), vjust = -1, size = 3) +
    theme_minimal() +
    labs(title = paste("PCA:", x, "vs", y))
}

# Generate and combine PCA plots
pca_plots <- list()
for (i in 1:6) {
  pca_plots[[i]] <- create_pca_plot(paste0("PC", i), paste0("PC", i+1))
}

# Arrange plots in a grid
combined_plot <- wrap_plots(pca_plots)

# Display and save the combined plot
print(combined_plot)
ggsave("combined_pca_plot.png", combined_plot, width = 14, height = 10)

"""## Differential Gene Expression Analysis Using DESeq2
# New Section
"""

#Install required packages (only needed once)
install.packages("BiocManager")
BiocManager::install("DESeq2")
BiocManager::install("EnhancedVolcano")  # For visualization

# Load libraries
library(DESeq2)
library(EnhancedVolcano)
library(ggplot2)

"""# Remove Duplicates from Ensemble ID column before mapping it with BioMart"""

# Load libraries
if (!requireNamespace("biomaRt", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("biomaRt")
library(biomaRt)
library(dplyr)  # for left_join()

# Load dataset
mdd_dataset <- read.csv("/content/GSE248260_white_matter_count_matrix.csv", header = TRUE, row.names = 1, sep = '\t')

# Clean Ensembl IDs
rownames(mdd_dataset) <- sub("\\..*", "", rownames(mdd_dataset))

# Connect to Ensembl
mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# Map Ensembl IDs to gene symbols
gene_mapping <- getBM(
  attributes = c("ensembl_gene_id", "hgnc_symbol"),
  filters = "ensembl_gene_id",
  values = rownames(mdd_dataset),
  mart = mart
)

# Turn rownames into a column temporarily
mdd_dataset <- mdd_dataset %>%
  tibble::rownames_to_column(var = "ensembl_gene_id")

# Merge safely
merged_counts <- left_join(mdd_dataset, gene_mapping, by = "ensembl_gene_id")

# Reorder columns: ensembl_gene_id | hgnc_symbol | samples
merged_counts <- merged_counts %>%
  select(ensembl_gene_id, hgnc_symbol, everything())

# Save to CSV
write.csv(merged_counts, "/content/cleaned_mdd_dataset_with_genesymbols.csv", row.names = FALSE)

# View
head(merged_counts)
dim(merged_counts)

# ------------------------------------------------
# Load required libraries
# ------------------------------------------------
install.packages("pheatmap")
library(DESeq2)
library(ggplot2)
library(pheatmap)

# ------------------------------------------------
# Step 1: Load Count Matrix
# ------------------------------------------------

# Read the count matrix
mdd_dataset <- read.csv("/content/GSE248260_white_matter_count_matrix.csv",
                        header = TRUE,
                        row.names = 1,
                        check.names = FALSE)

# Optional: Filter out lowly expressed genes
# Keep genes that have counts >1 in at least 3 samples
mdd_dataset <- mdd_dataset[rowSums(mdd_dataset > 1) >= 3, ]

# ------------------------------------------------
# Step 2: Create Metadata (Sample Information)
# ------------------------------------------------

# Get sample names (column names)
sample_names <- colnames(mdd_dataset)

# Now define which samples are "Normal" and which are "MDD"
normal_samples <- c("104A", "131A", "142A", "153A", "44A", "48A", "73A", "82A", "89A")  # Your Normal samples

# Assign condition
conditions <- ifelse(sample_names %in% normal_samples, "Normal", "MDD")

# Create metadata dataframe
meta_data <- data.frame(
  sample = sample_names,
  condition = factor(conditions, levels = c("Normal", "MDD"))  # Set "Normal" as reference
)

# Check metadata
print(meta_data)

#Step 3: Create DESeq2 object
# ------------------------------

dds <- DESeqDataSetFromMatrix(countData = mdd_dataset,
                              colData = colData,
                              design = ~ condition)
                              # Create DESeq dataset



dds

#Run Deseq analysis
DS_run <- DESeq(dds)
# Store the results of the analysis
res <- results(DS_run, contrast = c("condition", "MDD", "Normal"))
# Print out the results
print(res)

sum(res$padj < 0.08, na.rm = TRUE)

# 1. Load your data (you already did)
# mdd_dataset <- read.csv(...)
# colData <- read.csv(...)

# 2. Create DESeq2 dataset
dds <- DESeqDataSetFromMatrix(countData = mdd_dataset,
                              colData = colData,
                              design = ~ condition)

# 3. (IMPORTANT) Run DESeq to fit the model
dds <- DESeq(dds)   # ✅ YOU MISSED THIS LINE EARLIER!!

# 4. Get results
res <- results(dds)

# 5. Continue with removing version numbers
res$ensembl_id <- gsub("\\..*", "", rownames(res))

# 6. Load biomaRt
if (!requireNamespace("biomaRt", quietly = TRUE)) {
  install.packages("BiocManager")
  BiocManager::install("biomaRt")
}
library(biomaRt)

# 7. Connect to Ensembl
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# 8. Map Ensembl IDs to Gene Names
mapping <- getBM(attributes = c('ensembl_gene_id', 'hgnc_symbol'),
                 filters = 'ensembl_gene_id',
                 values = res$ensembl_id,
                 mart = ensembl)

# 9. Merge mapping
res_mapped <- merge(as.data.frame(res), mapping, by.x = "ensembl_id", by.y = "ensembl_gene_id", all.x = TRUE)

# 10. View the mapped results
head(res_mapped)

summary(rowSums(counts(dds)))

dds <- DESeq(dds)
res <- results(dds)

"""## Estimate the differential gene expression analysis again

## Sort the dataframe by padj value to find out stastically significant genes
"""

# Remove the hgnc_symbol column and keep gene_label
res_mapped <- res_mapped[, !(colnames(res_mapped) %in% c("hgnc_symbol"))]

# Optional: Reorder columns if needed
res_mapped <- res_mapped[, c("gene_label", setdiff(colnames(res_mapped), "gene_label"))]

# Preview the cleaned dataframe
head(res_mapped)

# Sort in ascending order of statistical significance
res_mapped[order(res_mapped$padj),]

# Sort by adjusted p-value
res_sorted <- res_mapped[order(res_mapped$padj), ]

# Select relevant columns: HGNC name, log2FC, p-value, padj
selected_columns <- res_sorted[, c("gene_label", "log2FoldChange", "pvalue", "padj")]

# Optionally rename columns for clarity
colnames(selected_columns) <- c("GeneName", "log2FoldChange", "PValue", "AdjustedPValue")

# Write to CSV
write.csv(selected_columns, file = "DEG_with_GeneNames.csv", row.names = FALSE)

# Step 1: Read the DEGs file
deg_data <- read.csv("DEG_with_GeneNames.csv", stringsAsFactors = FALSE)

# Step 2: Make sure 'AdjustedPValue' is numeric
deg_data$AdjustedPValue <- suppressWarnings(as.numeric(deg_data$AdjustedPValue))

# Step 3: Filter out rows with missing AdjustedPValue
deg_data_filtered <- deg_data[!is.na(deg_data$AdjustedPValue), ]

# Step 4: Sort by AdjustedPValue (ascending)
deg_data_sorted <- deg_data_filtered[order(deg_data_filtered$AdjustedPValue), ]

# Step 5: Extract top 50 DEGs
top_50_deg <- head(deg_data_sorted, 50)

# Step 6: Write to new CSV file
write.csv(top_50_deg, "Top_50_DEGs.csv", row.names = FALSE)

# Assuming you already have a top 50 dataframe
top15_from_top50 <- head(top_50_deg, 15)

# View the result
top15_from_top50

# Optional: Save it to CSV
write.csv(top15_from_top50, file = "top15_from_top50.csv", row.names = FALSE)

"""# MA PLOT"""

plotMA(res, Main = "DESeq2", ylim = c(-2,2), cex = 2)

"""
# find the min and max of log2fold change for plotting"""

summary(res$log2FoldChange)

"""# Volcano plot
The volcano plot summarises the differential gene expression analysis. NS (grey) : non significant genes Log2FC (green): gene with absolute fold change greater than 1 p value (blue) : genes that are statistically significant but no difference in the fold change p value and log2FC (red) : genes that are statistically significant and a difference in the fold change that is great than 1 in absolute scale.


"""

# Load the package
library(EnhancedVolcano)

# Create the plot
EnhancedVolcano(res,
                lab = rownames(res),              # Gene labels
                x = 'log2FoldChange',             # X-axis = log2 fold change
                y = 'padj',                       # Y-axis = adjusted p-value
                xlim = c(-3, 5),                  # X-axis limits
                pCutoff = 0.05,                   # Adjusted p-value threshold
                FCcutoff = 1,                     # Fold-change threshold (log2FC > 1 or < -1)
                pointSize = 2.0,                  # Size of points
                labSize = 3.5,                    # Size of gene labels
                col = c('grey30', 'forestgreen', 'royalblue', 'red2'),  # Color scheme
                legendLabels = c('NS','Log2FC','p-adj','p-adj & Log2FC'),
                legendPosition = 'right',
                title = 'Volcano Plot: DESeq2 Results',
                subtitle = 'MDD vs Normal',
                caption = 'Log2FC cutoff = 1; p-adj < 0.05',
                drawConnectors = TRUE,
                widthConnectors = 0.5)

"""# Output results in.txt format"""

pped

# Save DESeq2 results to a text file
write.table(res_mapped, "MDD_GSE248260.txt",
            row.names=TRUE, col.names=TRUE,
            sep="\t", quote=TRUE, append=TRUE)

"""# Functional Analysis
Installing and Loading Required Packages for Functional Analysis

# Gene Ontology (GO) Analysis
"""

data_file <- "/content/top15_from_top50.csv"  # Replace with your actual file name
deseq_results <- read.csv(data_file, header = TRUE, check.names = FALSE)

# Rename the first column to "GeneID"
colnames(deseq_results)[1] <- "GeneName"

# View the first few rows
head(deseq_results)

# Extract only the GeneID column
gene_id_df <- deseq_results["GeneName"]


# Write the extracted GeneID column to a new CSV file
write.csv(gene_id_df, file = "file_for_david", row.names = FALSE)